### ISSUE TITLE
validation mIoU is nan?

### ISSUE THREAD

**Issue by nikste** [WilhelmT/ClassMix#1]
Hi, I'm trying to run the default experiment on cityscapes with:
```python3 trainSSL.py --config ./configs/configSSL.json --name SSL```
as indicated in the readme.
It seems validatoin mIoU in tensorboard is `NaN` any idea what could be going wrong ?

**Comment by nikste** [comment]
it looks like it was rather quick to fix :)

**Comment by WilhelmT** [comment]
Could be some version issue, it still works fine for me. If others have a similar issue, I'll update it.

Thanks, closing.

**Comment by nikste** [comment]
sorry I'm confused here, what do you mean with version issue?
if you look into the code on the master branch `data_list` is created but not updated at all.
it goes into `get_iou` where its the basis for the computation of the confusion matrix.
So I'd really be curious how this would work on master, maybe you were on a different branch ?

**Comment by WilhelmT** [comment]
My bad, a line does appear to be missing. Good catch! :)
