### ISSUE TITLE
how to run it?

### ISSUE THREAD

**Issue by 775397252** [WilhelmT/ClassMix#3]
hi,README.md display that "python3 trainSSL.py --config ./configs/configSSL.json --name SSL",it doesn't run.
so，what the true practice?maybe more detail

**Comment by WilhelmT** [comment]
Hi,

Do you have more information on what type of errors you get?

Have you installed all the packages specified, and placed the data in the correct directories?

**Comment by 775397252** [comment]
My system is win10,and i use CityScapes  dataset.
error as follow:
```
Traceback (most recent call last):
  File "D:/Python/papers/ClassMix/trainSSL.py", line 659, in <module>
    main()
  File "D:/Python/papers/ClassMix/trainSSL.py", line 293, in main
    train_dataset = data_loader(data_path, is_transform=True, augmentations=data_aug, img_size=input_size)
  File "D:\Python\papers\ClassMix\data\cityscapes_loader.py", line 118, in __init__
    raise Exception(
Exception: No files for split=[train] found in ../data/CityScapes/leftImg8bit_trainvaltest\leftImg8bit\train
```
Can you provide VOC2012 config flie,such as configSSL.json?thanks a lot

**Comment by 775397252** [comment]
![image](https://user-images.githubusercontent.com/7972945/105143218-8012a800-5b36-11eb-8618-a16bf8a82843.png)
dataset
